# Generated by Django 6.0.7 on 2026-08-31 09:20

from django.db import migrations, models

import pined.django.db.migrations
import pined.django.db.models
import pined.django.serializers.json
import tests.testapp.schemas


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="device", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Terminal",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_software_version", models.CharField(default="0.0.0", max_length=32)),
                ("extra", models.JSONField(default=None, null=True)),
                (
                    "metadata",
                    pined.django.db.models.PydanticField(
                        tests.testapp.schemas.Metadata,
                        default=None,
                        encoder=pined.django.serializers.json.JSONEncoder,
                        null=True,
                    ),
                ),
            ],
        ),
        pined.django.db.migrations.AlterPydantic(
            model_name="terminal",
            name="metadata",
            schema_hash="d04118555669c90f",
        ),
    ]
