# Generated by Django 6.0.7 on 2026-08-31 09:20

from django.db import migrations

import pined.django.db.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        pined.django.db.migrations.AlterPydantic(
            model_name="terminal",
            name="metadata",
            schema_hash="5d9b714b77a2728b",
            previous_schema_hash="d04118555669c90f",
            # `region` is new and required, so every row has to be given one.
            # `max_backup` is new and merely has a default, so 20 lands
            # everywhere the row does not already say otherwise.
            forwards_defaults={"region": "eu", "max_backup": 20},
        ),
    ]
