# Generated by Django 6.0.7 on 2026-08-31 09:21

from django.db import migrations

import pined.django.db.migrations
from pined.django.db.migrations import F, P, R


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_metadata_defaults"),
    ]

    operations = [
        pined.django.db.migrations.AlterPydantic(
            model_name="terminal",
            name="metadata",
            schema_hash="cf5ac43595503dd9",
            previous_schema_hash="5d9b714b77a2728b",
            forwards_defaults={
                # straight off the parent model's column of the same name
                "current_software_version": F("current_software_version"),
                # `os_version` keeps its value under its new name
                "android_version": R("os_version"),
                # reads what `R` just produced, since `P` resolves last
                "also_version": P("android_version"),
                # dug out of the `extra` JSONField, 0 where the path is absent
                "update_attempts": F("extra.software.update_attempts", 0),
            },
            backwards_defaults={"os_version": R("android_version")},
        ),
    ]
