# Generated by Django 6.0.7 on 2026-08-31 09:21

from django.db import migrations

import pined.django.db.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_metadata_expressions"),
    ]

    operations = [
        pined.django.db.migrations.AlterPydantic(
            model_name="terminal",
            name="metadata",
            schema_hash="9954de6e7538383c",
            previous_schema_hash="cf5ac43595503dd9",
            forwards_defaults={"max_backup": 50, "log_retention": 14, "region": "xx"},
            # `max_backup` is forced everywhere, user data included. The other
            # two only reach rows that never moved off the default.
            override_fields=["max_backup"],
        ),
    ]
