# Generated by Django 6.0.7 on 2026-08-31 09:21

from typing import Any

from django.db import migrations

import pined.django.db.migrations


def fold_also_version(data: dict[str, Any]) -> dict[str, Any]:
    """
    Fold `also_version` into `android_version` before it disappears.

    Neither defaults nor renames can express this: the value only moves
    where `android_version` never got one of its own.
    """

    also = data.pop("also_version", None)
    if also and data.get("android_version") in (None, "unknown"):
        data["android_version"] = also
    return data


def unfold_also_version(data: dict[str, Any]) -> dict[str, Any]:
    """
    Hand `also_version` its key back, mirroring the fold.
    """

    data["also_version"] = data.get("android_version", "unknown")
    return data


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_metadata_override"),
    ]

    operations = [
        pined.django.db.migrations.AlterPydantic(
            model_name="terminal",
            name="metadata",
            schema_hash="f6f354d12d0e9bec",
            previous_schema_hash="9954de6e7538383c",
            forwards_transform=fold_also_version,
            backwards_transform=unfold_also_version,
        ),
    ]
